### ISSUE TITLE
Missing email when authenticating with GitHub

### ISSUE THREAD

**Issue by skjvkjvsdkjvdlfkvdfv** [thoughtbot/yesod-auth-oauth2#69]
Hi, Haskell newbie here.

I'm using both this repository and the Carnival repository to learn how to authenticate a user with GitHub and save their email address. There are a few clues in the code that would suggest GitHub can potentially not return an email address for a user, like [here](https://github.com/thoughtbot/yesod-auth-oauth2/blob/master/Yesod/Auth/OAuth2/Github.hs#L41).

Am I understanding this correctly? If that's the case, how do you handle a missing email address? Do you just authenticate the user anyway without an email address? [This line](https://github.com/thoughtbot/carnival/blob/master/Model/User.hs#L132) seems to suggest that in case no email address is found, you just throw an exception; you'd have to otherwise [this line](https://github.com/thoughtbot/carnival/blob/master/config/models#L21) would have to be a `Text Maybe` rather than just a `Text`, right?

**Comment by jezen** [comment]
Of course I forgot to sign into my real account when submitting this issue… 😞

**Comment by pbrisbin** [comment]
As you noticed, we do [throw](https://github.com/thoughtbot/yesod-auth-oauth2/blob/master/Yesod/Auth/OAuth2/Github.hs#L94) an `InvalidProfileResponse` if we can't determine an email for the authenticating user. This will materialize as a 500 in Carnival, though we did at one time intend to `catch` it and do something more graceful. Since we either get an email or 500, we can require and assume an email exists for users on the Carnival side.

[This line](https://github.com/thoughtbot/carnival/blob/master/Model/User.hs#L132) really only matters coincidentally. It's meant to catch other missing keys but we also use it to look up the `"email"` key because we have to resolve the `Maybe` anyway, even though we know we'll either have the value or would've already experienced an exception at that point.

There are a few bugs here around "public" email that may be causing confusion: in addition to the emails in the `/emails` response, a user can specify a public email that will appear in the `/user` response directly. This is what we're parsing [here](https://github.com/thoughtbot/yesod-auth-oauth2/blob/master/Yesod/Auth/OAuth2/Github.hs#L51). Unfortunately we're doing two things wrong (IMO):

1. We're adding to extras [here](https://github.com/thoughtbot/yesod-auth-oauth2/blob/master/Yesod/Auth/OAuth2/Github.hs#L110) as a duplicate `email` key. That's a bug introduced in [this](https://github.com/thoughtbot/yesod-auth-oauth2/commit/64b65ca4c6b6c3e6f402b31a682f52124beef4a7) refactor
1. If we have that, but `/emails` is empty, that could still be considered valid by returning that as the `email` value in extras -- but it's an exception today

/cc @jferris 

Anyway, hope this helps.

**Comment by jezen** [comment]
@pbrisbin Ah, ok, so the reason I'm not getting an email address back in my JSON response is because the two key names (`email`) are colliding?

If so, is it a simple case of renaming one of the keys? _i.e._ :

```
toCreds :: GithubUser -> [GithubUserEmail] -> AccessToken -> Creds m
toCreds user userMails token = Creds
    { credsPlugin = "github"
    -- ...
    , credsExtra =
        [ ("email", githubUserEmailAddress email)
        -- ...
        ]
        ++ maybeExtra "email_public" (githubUserPublicEmail user)
    }
```

Or would that have implications for other people who are using this library?

**Comment by pbrisbin** [comment]
Yeah it's just a bug, you can see in the refactor commit I linked that we accidentally renamed that second value's key from [`public_email`](https://github.com/thoughtbot/yesod-auth-oauth2/commit/64b65ca4c6b6c3e6f402b31a682f52124beef4a7#diff-c9f1235836d5a54b83893cf15325db4dL121) to [`email`](https://github.com/thoughtbot/yesod-auth-oauth2/commit/64b65ca4c6b6c3e6f402b31a682f52124beef4a7#diff-c9f1235836d5a54b83893cf15325db4dR110). We just need to put that back. If it has implications for other users of this library, that's because they're in the same boat as you and would really like the fix :)

**Comment by skjvkjvsdkjvdlfkvdfv** [comment]
@pbrisbin Ok, great 😄  Is there anything I can do to help?

**Comment by pbrisbin** [comment]
If you wanted to open that fix as a PR that would certainly speed things up, otherwise I'll try to get to it when I can.

**Comment by jezen** [comment]
@pbrisbin I fixed that line and added a minor version bump in https://github.com/thoughtbot/yesod-auth-oauth2/pull/70.

Is there anything else my PR should contain?

**Comment by pbrisbin** [comment]
v0.2.1 released with the creds-extra key fixed.
